name: CMake_ARM

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    timeout-minutes: 20
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        include:
          - arch: armv7
            distro: ubuntu18.04
          - arch: aarch64
            distro: ubuntu18.04

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: recursive

    # - name: Checkout submodules
    #   run: git submodule update --init --recursive --recommend-shallow --depth 1

    - uses: uraimo/run-on-arch-action@v2.0.5
      name: Build
      id: build
      with:
        arch: ${{ matrix.arch }}
        distro: ${{ matrix.distro }}
        shell: /bin/sh
        install: |
          case "${{ matrix.distro }}" in
            ubuntu*|jessie|stretch|buster|bullseye)
              apt-get update -q -y
              apt-get install -q -y git build-essential cmake
              ;;
            fedora*)
              dnf -y update
              dnf -y install git which
              ;;
            alpine*)
              apk update
              apk add git
              ;;
          esac

        run: |
          uname -a
          pwd
          ls
          mkdir -p build
          cd build
          cmake ..
          make
          ctest
