name: Release

# on:
#   push:
#     tags: '*'
on:
  push:
    # branches: [ master ]
    tags: '*'

env:
  BUILD_TYPE: Release

jobs:
  build:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            exe_name: main
            artifact_name: main_linux_x64.tgz
          - os: windows-latest
            exe_name: main.exe
            artifact_name: main_windows_x64.zip
          # - os: macOS-latest
          #   exe_name: main
          #   artifact_name: main_mac_darwin.tgz

    steps:
    - uses: actions/checkout@v2
    - name: Checkout Submodules
      run: |
        git config --global http.postBuffer 100M
        git submodule update --init --recursive --recommend-shallow --depth 1
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Package
      if: startsWith(github.ref, 'refs/tags/')
      shell: bash
      run: |
        ls  ${{github.workspace}}/build
        if [[ "${{ matrix.os }}" == "windows-latest" ]]
        then
          7z a ${{ matrix.artifact_name }} ${{github.workspace}}/build/${{ matrix.exe_name }}
        else
          tar czvf ${{ matrix.artifact_name }} ${{github.workspace}}/build/${{ matrix.exe_name }}
        fi
        ls

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        body_path: CHANGELOG.md
        files: |
          main_*
          LICENSE
          NOTICE.md


# jobs:
#   build:
#     name: Create Release
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Create Release
#       id: create_release
#       uses: actions/create-release@v1
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
#       with:
#         tag_name: ${{ github.ref }}
#         release_name: Release ${{ github.ref }}
#         body_path: CHANGELOG.md
#         draft: false
#         prerelease: false
#     - name: Upload Release Asset
#       id: upload-release-asset 
#       uses: actions/upload-release-asset@v1
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         upload_url: ${{ steps.create_release.outputs.upload_url }}
#         asset_path: ./bin/azblogfilter.linux-amd64.tar.gz
#         asset_name: azblogfilter.linux-amd64.tar.gz
#         asset_content_type: application/gzip

#     - name: Build Artifacts
#       run: |
#         cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_TESTS=OFF
#         cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

#     - name: Upload Release Asset
#       uses: actions/upload-artifact@v2
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
#       with:
#         upload_url: ${{ steps.create_release.outputs.upload_url }}
#         asset_path: ./bin/azblogfilter.linux-amd64.tar.gz
#         asset_name: azblogfilter.linux-amd64.tar.gz
#         asset_content_type: application/gzip